# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_app', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=264)),
                ('hero_image', models.ImageField(upload_to='hero_image_pics')),
                ('publish_date', models.DateField()),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping_app.Author')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping_app.Subject')),
            ],
        ),
    ]
