# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_app', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(max_length=200, upload_to='hero_image_pics'),
        ),
    ]
